// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/demo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_proto_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateShortURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_proto_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_proto_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_proto_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type InputManyUrlsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputManyUrlsItem) Reset() {
	*x = InputManyUrlsItem{}
	mi := &file_proto_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputManyUrlsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputManyUrlsItem) ProtoMessage() {}

func (x *InputManyUrlsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputManyUrlsItem.ProtoReflect.Descriptor instead.
func (*InputManyUrlsItem) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{4}
}

func (x *InputManyUrlsItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InputManyUrlsItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type OutputManyUrlsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputManyUrlsItem) Reset() {
	*x = OutputManyUrlsItem{}
	mi := &file_proto_demo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputManyUrlsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputManyUrlsItem) ProtoMessage() {}

func (x *OutputManyUrlsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputManyUrlsItem.ProtoReflect.Descriptor instead.
func (*OutputManyUrlsItem) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{5}
}

func (x *OutputManyUrlsItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *OutputManyUrlsItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*InputManyUrlsItem   `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_proto_demo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{6}
}

func (x *ShortenBatchRequest) GetUrls() []*InputManyUrlsItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ShortenBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*OutputManyUrlsItem  `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_proto_demo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{7}
}

func (x *ShortenBatchResponse) GetUrls() []*OutputManyUrlsItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ShortenBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserUrlsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUrlsItem) Reset() {
	*x = UserUrlsItem{}
	mi := &file_proto_demo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUrlsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsItem) ProtoMessage() {}

func (x *UserUrlsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsItem.ProtoReflect.Descriptor instead.
func (*UserUrlsItem) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{8}
}

func (x *UserUrlsItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserUrlsItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUserUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserUrlsRequest) Reset() {
	*x = GetUserUrlsRequest{}
	mi := &file_proto_demo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUrlsRequest) ProtoMessage() {}

func (x *GetUserUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUrlsRequest.ProtoReflect.Descriptor instead.
func (*GetUserUrlsRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserUrlsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUrls      []*UserUrlsItem        `protobuf:"bytes,1,rep,name=user_urls,json=userUrls,proto3" json:"user_urls,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserUrlsResponse) Reset() {
	*x = GetUserUrlsResponse{}
	mi := &file_proto_demo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUrlsResponse) ProtoMessage() {}

func (x *GetUserUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUrlsResponse.ProtoReflect.Descriptor instead.
func (*GetUserUrlsResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserUrlsResponse) GetUserUrls() []*UserUrlsItem {
	if x != nil {
		return x.UserUrls
	}
	return nil
}

func (x *GetUserUrlsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteUserUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserUrlsRequest) Reset() {
	*x = DeleteUserUrlsRequest{}
	mi := &file_proto_demo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserUrlsRequest) ProtoMessage() {}

func (x *DeleteUserUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserUrlsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserUrlsRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserUrlsRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

func (x *DeleteUserUrlsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserUrlsResponse) Reset() {
	*x = DeleteUserUrlsResponse{}
	mi := &file_proto_demo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserUrlsResponse) ProtoMessage() {}

func (x *DeleteUserUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserUrlsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserUrlsResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserUrlsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_demo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{13}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_demo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_demo_proto protoreflect.FileDescriptor

const file_proto_demo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/demo.proto\x12\tshortener\"S\n" +
	"\x15CreateShortURLRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x16CreateShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x15GetOriginalURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\";\n" +
	"\x16GetOriginalURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"]\n" +
	"\x11InputManyUrlsItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"X\n" +
	"\x12OutputManyUrlsItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"`\n" +
	"\x13ShortenBatchRequest\x120\n" +
	"\x04urls\x18\x01 \x03(\v2\x1c.shortener.InputManyUrlsItemR\x04urls\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"_\n" +
	"\x14ShortenBatchResponse\x121\n" +
	"\x04urls\x18\x01 \x03(\v2\x1d.shortener.OutputManyUrlsItemR\x04urls\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\fUserUrlsItem\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"-\n" +
	"\x12GetUserUrlsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\x13GetUserUrlsResponse\x124\n" +
	"\tuser_urls\x18\x01 \x03(\v2\x17.shortener.UserUrlsItemR\buserUrls\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x15DeleteUserUrlsRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\tR\tshortUrls\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x16DeleteUserUrlsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x11\n" +
	"\x0fGetStatsRequest\"(\n" +
	"\x10GetStatsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xef\x03\n" +
	"\x04Urls\x12U\n" +
	"\x0eCreateShortURL\x12 .shortener.CreateShortURLRequest\x1a!.shortener.CreateShortURLResponse\x12U\n" +
	"\x0eGetOriginalURL\x12 .shortener.GetOriginalURLRequest\x1a!.shortener.GetOriginalURLResponse\x12O\n" +
	"\fShortenBatch\x12\x1e.shortener.ShortenBatchRequest\x1a\x1f.shortener.ShortenBatchResponse\x12L\n" +
	"\vGetUserUrls\x12\x1d.shortener.GetUserUrlsRequest\x1a\x1e.shortener.GetUserUrlsResponse\x12U\n" +
	"\x0eDeleteUserUrls\x12 .shortener.DeleteUserUrlsRequest\x1a!.shortener.DeleteUserUrlsResponse\x12C\n" +
	"\bGetStats\x12\x1a.shortener.GetStatsRequest\x1a\x1b.shortener.GetStatsResponseB,Z*github.com/sheinsviatoslav/shortener/protob\x06proto3"

var (
	file_proto_demo_proto_rawDescOnce sync.Once
	file_proto_demo_proto_rawDescData []byte
)

func file_proto_demo_proto_rawDescGZIP() []byte {
	file_proto_demo_proto_rawDescOnce.Do(func() {
		file_proto_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_demo_proto_rawDesc), len(file_proto_demo_proto_rawDesc)))
	})
	return file_proto_demo_proto_rawDescData
}

var file_proto_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_demo_proto_goTypes = []any{
	(*CreateShortURLRequest)(nil),  // 0: shortener.CreateShortURLRequest
	(*CreateShortURLResponse)(nil), // 1: shortener.CreateShortURLResponse
	(*GetOriginalURLRequest)(nil),  // 2: shortener.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil), // 3: shortener.GetOriginalURLResponse
	(*InputManyUrlsItem)(nil),      // 4: shortener.InputManyUrlsItem
	(*OutputManyUrlsItem)(nil),     // 5: shortener.OutputManyUrlsItem
	(*ShortenBatchRequest)(nil),    // 6: shortener.ShortenBatchRequest
	(*ShortenBatchResponse)(nil),   // 7: shortener.ShortenBatchResponse
	(*UserUrlsItem)(nil),           // 8: shortener.UserUrlsItem
	(*GetUserUrlsRequest)(nil),     // 9: shortener.GetUserUrlsRequest
	(*GetUserUrlsResponse)(nil),    // 10: shortener.GetUserUrlsResponse
	(*DeleteUserUrlsRequest)(nil),  // 11: shortener.DeleteUserUrlsRequest
	(*DeleteUserUrlsResponse)(nil), // 12: shortener.DeleteUserUrlsResponse
	(*GetStatsRequest)(nil),        // 13: shortener.GetStatsRequest
	(*GetStatsResponse)(nil),       // 14: shortener.GetStatsResponse
}
var file_proto_demo_proto_depIdxs = []int32{
	4,  // 0: shortener.ShortenBatchRequest.urls:type_name -> shortener.InputManyUrlsItem
	5,  // 1: shortener.ShortenBatchResponse.urls:type_name -> shortener.OutputManyUrlsItem
	8,  // 2: shortener.GetUserUrlsResponse.user_urls:type_name -> shortener.UserUrlsItem
	0,  // 3: shortener.Urls.CreateShortURL:input_type -> shortener.CreateShortURLRequest
	2,  // 4: shortener.Urls.GetOriginalURL:input_type -> shortener.GetOriginalURLRequest
	6,  // 5: shortener.Urls.ShortenBatch:input_type -> shortener.ShortenBatchRequest
	9,  // 6: shortener.Urls.GetUserUrls:input_type -> shortener.GetUserUrlsRequest
	11, // 7: shortener.Urls.DeleteUserUrls:input_type -> shortener.DeleteUserUrlsRequest
	13, // 8: shortener.Urls.GetStats:input_type -> shortener.GetStatsRequest
	1,  // 9: shortener.Urls.CreateShortURL:output_type -> shortener.CreateShortURLResponse
	3,  // 10: shortener.Urls.GetOriginalURL:output_type -> shortener.GetOriginalURLResponse
	7,  // 11: shortener.Urls.ShortenBatch:output_type -> shortener.ShortenBatchResponse
	10, // 12: shortener.Urls.GetUserUrls:output_type -> shortener.GetUserUrlsResponse
	12, // 13: shortener.Urls.DeleteUserUrls:output_type -> shortener.DeleteUserUrlsResponse
	14, // 14: shortener.Urls.GetStats:output_type -> shortener.GetStatsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_demo_proto_init() }
func file_proto_demo_proto_init() {
	if File_proto_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_demo_proto_rawDesc), len(file_proto_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_demo_proto_goTypes,
		DependencyIndexes: file_proto_demo_proto_depIdxs,
		MessageInfos:      file_proto_demo_proto_msgTypes,
	}.Build()
	File_proto_demo_proto = out.File
	file_proto_demo_proto_goTypes = nil
	file_proto_demo_proto_depIdxs = nil
}
